#!/usr/bin/env bash

set -x
set -e

CONF=$1
if [ -z "${CONF}" ]; then
	CONF=mshv_defconfig
fi

SOURCE_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "${SOURCE_ROOT}"

ARCH=$(uname -p)
case "${ARCH}" in
	aarch64)
		ARCH="arm64"
		ARCHDIR="arm64"
		;;
	x86_64)
		ARCH="x86_64"
		ARCHDIR="x86"
		;;
	*)
		echo "Unsupported architecture '${ARCH}'"
		exit 1
		;;
esac

make mrproper

cp "arch/${ARCHDIR}/configs/${CONF}" .config
make LC_ALL= ARCH=${ARCH} olddefconfig

diff -u "arch/${ARCHDIR}/configs/${CONF}" .config
