#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import _init  # noqa F401
from lsgtools import log
from lsgtools import cli
from lsgtools import ado
from lsgtools.virt.mshv import kernel

def_specs = {"uvm": True, "uvm-cvm": True}
def spec_opts(arg):
    global def_specs
    ret = def_specs
    if None is arg:
        return ret
    arg_lst = arg.split(",")
    for e in arg_lst:
        if not "uvm" == e and not "uvm-cvm" == e:
            raise Exception("Unknown value '{}' for --specs".format(e))
    ret["uvm"] = "uvm" in arg_lst;
    ret["uvm-cvm"] = "uvm-cvm" in arg_lst;

    return ret

arg_parser = cli.create_arg_parser(prog="kernel-spec-pr",
                                   description="File a PR in lsg-linux-mariner for the specific branch")
arg_parser.add_argument("--ado-org", help="Name of the Azure DevOps organization", required=True)
arg_parser.add_argument("--ado-project", help="Name of the Azure DevOps project", required=True)
arg_parser.add_argument("--ado-access-token", help="Azure DevOps access token", required=True)
arg_parser.add_argument("--token-type", help="Token type: PAT or OAUTH", default="OAUTH")
arg_parser.add_argument("--repo-id", help="Repository ID", required=True)
arg_parser.add_argument("--source-branch", help="Source branch of the pull request", required=True)
arg_parser.add_argument("--tag", help="Tag name", required=True)
arg_parser.add_argument("--revision", help="Git revision hash", required=True)
arg_parser.add_argument("--build-requestedfor-id", help="Id of the person who checked in the changes", required=True)
arg_parser.add_argument("--specs", type=spec_opts, action="store", required=False,
                        default=def_specs, help="Comma separated list of [uvm, uvm-cvm]")
args = arg_parser.parse_args()
log.set_verbosity(args.verbose)
ado.init_defaults(args.ado_org, args.ado_project, args.repo_id, None,
                  args.token_type, args.ado_access_token)


commit_msg_tag = ""
if args.specs["uvm"]:
    commit_msg_tag = "{} {}:".format(commit_msg_tag, "kernel-uvm")
if args.specs["uvm-cvm"]:
    commit_msg_tag = "{} {}:".format(commit_msg_tag, "kernel-uvm-cvm")

source_branch = args.source_branch
if not source_branch.startswith("refs/heads/"):
    source_branch = "refs/heads/{}".format(source_branch)
payload = {
    "sourceRefName": source_branch,
    "targetRefName": "refs/heads/main-3.0",
    "title": "{} Autoupdate to {}".format(commit_msg_tag.strip(), kernel.get_version_from_tag(args.tag)),
    "description": "Kernel revision: {}".format(args.revision),
    "autoCompleteSetBy": {
            "id": args.build_requestedfor_id
    },
    "completionOptions": {
        "deleteSourceBranch": True,
        "mergeStrategy": "rebaseMerge",
        "squashMerge": False,
        "bypassPolicy": False
    }
}

try:
    if ado.pr_create(payload=payload):
        exit(0)
    raise Exception("Failed to create PR")
except Exception as e:
    log.fatal("{}".format(e))
    exit(1)
