#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import os
import sys
import requests
import subprocess
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))  # noqa E402

from lsgtools import log  # noqa E402
from lsgtools import cli  # noqa E402
from lsgtools.virt import conf  # noqa E402
from lsgtools.virt.mshv import kernel  # noqa E402

arg_parser = cli.create_arg_parser(prog="kernel-spec-update",
                                   description="Update SPEC file in lsg-linux-mariner derivative repo")
# Ref might look like refs/tags/msft/mshv-rolling/5.15.74.mshv3.
arg_parser.add_argument("tag", action="store", help="Tag name")
arg_parser.add_argument("rev", action="store", help="Git revision hash")
args = arg_parser.parse_args()
log.set_verbosity(args.verbose)

version = kernel.get_version_from_tag(args.tag)
# TODO if possible, verify the passed  kernel commit hash
# TODO for this to work locally need to retrieve the hash if not passed
rev_hash = args.rev[:8]
if len(rev_hash) < 8:
    log.err("Git revision '{}' is invalid".format(rev_hash))
    exit(1)

derivative_branch = "autoupdate/kernel-uvm-{}".format(version)
storage_url = os.getenv("SOURCES_STORAGE_URL")
if storage_url is None:
    storage_url = conf.default_storage_url

tarball_name = kernel.build_tgz_name(version, "uvm")
tarball_local_path = "/tmp/{}".format(tarball_name)
tarball_url = "{}/{}".format(storage_url, tarball_name)
tarball_sum_url = "{}/{}.sha256".format(storage_url, tarball_name)

try:
    # This simultaneously also serves as a download test for the tarball
    resp = requests.get(tarball_url)
    if not 200 == resp.status_code:
        raise Exception(resp.content)
    with open(tarball_local_path, 'wb') as f:
        f.write(resp.content)
    f.close()
except Exception as e:
    log.fatal("Couldn't retvieve tarball '{}'.\nException: {}".format(tarball_url, e))
    exit(1)

try:
    resp = requests.get(tarball_sum_url)
    tarball_sha256 = resp.content.strip().decode()
    if not 200 == resp.status_code:
        raise Exception(tarball_sha256)
except Exception as e:
    log.fatal("Couldn't retvieve the SHA256 sum file '{}'.\nException: {}").format(tarball_sum_url, e)
    exit(1)

cmd = ["git", "checkout", "-b", derivative_branch]
res = subprocess.run(cmd)
if 0 != res.returncode:
    err = res.stderr.decode("ascii")
    raise Exception(err)


# Update kernel-uvm.spec
kernel_spec_path = "SPECS/kernel/kernel-uvm.spec"
kernel_sums_path = "SPECS/kernel/kernel-uvm.signatures.json"
kernel_conf = {
        "x86": {"path": "SPECS/kernel/config_uvm_x86", "sha256": None, "kernel_arch": "x86"},
        "aarch64": {"path": "SPECS/kernel/config_uvm_aarch64", "sha256": None, "kernel_arch": "arm64"}
        }
kernel_conf_patch = [
    ["Linux/(.*) (.*) Kernel Configuration", "Linux/\\1 {} Kernel Configuration".format(version)]
]
kernel_conf = kernel.patch_config(tarball_local_path, kernel_conf, kernel_conf_patch, "uvm_defconfig")
# Re-create signatures file
sums_struct = {
    "Signatures": {
        os.path.basename(kernel_conf["x86"]["path"]): kernel_conf["x86"]["sha256"],
        os.path.basename(kernel_conf["aarch64"]["path"]): kernel_conf["aarch64"]["sha256"],
        tarball_name: tarball_sha256,
            }
    }
kernel.update_spec_sums(kernel_sums_path, sums_struct)
# Update spec
kernel.update_spec(kernel_spec_path, version, rev_hash)


# Update kernel-uvm-cvm.spec
kernel_spec_path = "SPECS/kernel/kernel-uvm-cvm.spec"
kernel_sums_path = "SPECS/kernel/kernel-uvm-cvm.signatures.json"
del kernel_conf["aarch64"]
# Re-create signatures file
sums_struct = {
    "Signatures": {
        os.path.basename(kernel_conf["x86"]["path"]): kernel_conf["x86"]["sha256"],
        tarball_name: tarball_sha256,
            }
    }
kernel.update_spec_sums(kernel_sums_path, sums_struct)
# Update spec
kernel.update_spec(kernel_spec_path, version, rev_hash)


# Commit the branch
commit_msg = """kernel-uvm: Autoupdate to {}

Kernel revision: {}
""".format(version, rev_hash)
cmd = ["git", "commit", "-a", "-m", commit_msg]
res = subprocess.run(cmd)
if 0 != res.returncode:
    err = res.stderr.decode("ascii")
    raise Exception(err)
