#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import os
import hashlib
import subprocess

import _init  # noqa F401
from lsgtools import log
from lsgtools import cli
from lsgtools.virt.mshv import kernel

arg_parser = cli.create_arg_parser(prog="kernel-spec-update",
                                   description="Update SPEC file in lsg-linux-mariner derivative repo")
# Ref might look like refs/tags/msft/mshv-rolling/5.15.74.mshv3.
arg_parser.add_argument("--tag", action="store", help="Tag name")
arg_parser.add_argument("--rev", action="store", help="Git revision hash")
arg_parser.add_argument("--tgz", action="store", help="Path to tarball file")
arg_parser.add_argument("--sha256", action="store", help="Path to checksum file")
args = arg_parser.parse_args()
log.set_verbosity(args.verbose)

version = kernel.get_version_from_tag(args.tag)
# TODO if possible, verify the passed  kernel commit hash
# TODO for this to work locally need to retrieve the hash if not passed
rev_hash = args.rev[:8]
if len(rev_hash) < 8:
    log.err("Git revision '{}' is invalid".format(rev_hash))
    exit(1)

derivative_branch = "autoupdate/kernel-mshv-{}".format(version)

tarball_name = args.tgz
with open(args.sha256, "r") as f:
    tarball_sha256 = f.read().strip()

cmd = ["git", "checkout", "-b", derivative_branch]
res = subprocess.run(cmd)
if 0 != res.returncode:
    err = res.stderr.decode("ascii")
    raise Exception(err)


# Update kernel-mshv.spec
kernel_spec_path = "SPECS/kernel/kernel-mshv.spec"
kernel_sums_path = "SPECS/kernel/kernel-mshv.signatures.json"
kernel_conf = {
        "x86": {"path": "SPECS/kernel/config_x86", "sha256": None, "kernel_arch": "x86"},
        "aarch64": {"path": "SPECS/kernel/config_aarch64", "sha256": None, "kernel_arch": "arm64"}
        }
kernel_conf_patch = [
    ["CONFIG_SYSTEM_TRUSTED_KEYS=.*", 'CONFIG_SYSTEM_TRUSTED_KEYS="certs/mariner.pem"'],
    ["Linux/(.*) (.*) Kernel Configuration", "Linux/\\1 {} Kernel Configuration".format(version)]
]
kernel_conf = kernel.patch_config(tarball_name, kernel_conf, kernel_conf_patch, "mshv_defconfig")
# Recalculate sum
pem_path = "SPECS/kernel/cbl-mariner-ca-20211013.pem"
with open(pem_path, "rb") as f:
    pem_sha256 = hashlib.sha256(f.read()).hexdigest()
grub_cfg_path_x86_64 = "SPECS/kernel/mariner_mshv.cfg_x86_64"
with open(grub_cfg_path_x86_64, "rb") as f:
    grub_cfg_sha256_x86_64 = hashlib.sha256(f.read()).hexdigest()
grub_menuentry_path_x86_64 = "SPECS/kernel/mariner_mshv_menuentry_x86_64"
with open(grub_menuentry_path_x86_64, "rb") as f:
    grub_menuentry_sha256_x86_64 = hashlib.sha256(f.read()).hexdigest()
grub_cfg_path_aarch64 = "SPECS/kernel/mariner_mshv.cfg_arm64"
with open(grub_cfg_path_aarch64, "rb") as f:
    grub_cfg_sha256_aarch64 = hashlib.sha256(f.read()).hexdigest()
grub_menuentry_path_aarch64 = "SPECS/kernel/mariner_mshv_menuentry_arm64"
with open(grub_menuentry_path_aarch64, "rb") as f:
    grub_menuentry_sha256_aarch64 = hashlib.sha256(f.read()).hexdigest()
# Re-create signatures file
sums_struct = {
    "Signatures": {
        os.path.basename(pem_path): pem_sha256,
        os.path.basename(kernel_conf["x86"]["path"]): kernel_conf["x86"]["sha256"],
        os.path.basename(kernel_conf["aarch64"]["path"]): kernel_conf["aarch64"]["sha256"],
        os.path.basename(tarball_name): tarball_sha256,
        os.path.basename(grub_cfg_path_x86_64): grub_cfg_sha256_x86_64,
        os.path.basename(grub_menuentry_path_x86_64): grub_menuentry_sha256_x86_64,
        os.path.basename(grub_cfg_path_aarch64): grub_cfg_sha256_aarch64,
        os.path.basename(grub_menuentry_path_aarch64): grub_menuentry_sha256_aarch64,
            }
    }
kernel.update_spec_sums(kernel_sums_path, sums_struct)
# Update spec
kernel.update_spec(kernel_spec_path, version, rev_hash)


# Update kernel-mshv-headers.spec
kernel_spec_path = "SPECS/kernel/kernel-mshv-headers.spec"
kernel_sums_path = "SPECS/kernel/kernel-mshv-headers.signatures.json"
# Re-create signatures file
sums_struct = {
    "Signatures": {
        os.path.basename(tarball_name): tarball_sha256,
        }
    }
kernel.update_spec_sums(kernel_sums_path, sums_struct)
# Update spec
kernel.update_spec(kernel_spec_path, version, rev_hash)


# Commit the branch
commit_msg = """kernel-msft: Autoupdate to {}

Kernel revision: {}
""".format(version, rev_hash)
cmd = ["git", "commit", "-a", "-m", commit_msg]
res = subprocess.run(cmd)
if 0 != res.returncode:
    err = res.stderr.decode("ascii")
    raise Exception(err)
