#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import _init  # noqa F401
from lsgtools import log
from lsgtools import cli
from lsgtools import ado
from lsgtools.virt.mshv import kernel

arg_parser = cli.create_arg_parser(prog="kernel-version-update-pr",
                                   description="File a PR in linux-dom0 for the specific branch")
arg_parser.add_argument("--ado-org", help="Name of the Azure DevOps organization", required=True)
arg_parser.add_argument("--ado-project", help="Name of the Azure DevOps project", required=True)
arg_parser.add_argument("--ado-access-token", help="Azure DevOps access token", required=True)
arg_parser.add_argument("--token-type", help="Token type: PAT or OAUTH", default="OAUTH")
arg_parser.add_argument("--repo-id", help="Repository ID", required=True)
arg_parser.add_argument("--source-branch", help="Source branch of the pull request", required=True)
arg_parser.add_argument("--new-version", help="New version the target branch to be updated to", required=True)
arg_parser.add_argument("--build-requestedfor-id", help="Id of the person who checked in the changes", required=True)
args = arg_parser.parse_args()
log.set_verbosity(args.verbose)
ado.init_defaults(args.ado_org, args.ado_project, args.repo_id, None,
                  args.token_type, args.ado_access_token)

if not kernel.is_version_valid(args.new_version):
    log.fatal("Invalid kernel version '{}'".format(args.new_version))
    exit(1)

source_branch = args.source_branch
if not source_branch.startswith("refs/heads/"):
    source_branch = "refs/heads/{}".format(source_branch)
payload = {
    "sourceRefName": source_branch,
    "targetRefName": "refs/heads/msft-uvm-main",
    "title": "makefile: config: Update version {}".format(kernel.get_version_from_tag(args.new_version)),
    "description": "Prepare to tag: msft/mshv-rolling/{}".format(args.new_version),
    "completionOptions": {
        "deleteSourceBranch": True,
        "mergeStrategy": "rebaseMerge",
        "squashMerge": False,
        "bypassPolicy": False
    }
}

try:
    if ado.pr_create(payload=payload):
        exit(0)
    raise Exception("Failed to create PR")
except Exception as e:
    log.fatal("{}".format(e))
    exit(1)
