#!/usr/bin/env bash

set -x
set -e

tdnf update -y
tdnf install -y gcc make diffutils binutils glibc-devel dwarves \
		kernel-headers flex bison python3-devel \
		openssl-devel bc awk perl python3-requests \
		python3-pip git ca-certificates systemtap-sdt-devel \
		libunwind-devel slang libcap-devel libnuma-devel \
		libbabeltrace2-devel msopenjdk-11 libtraceevent-devel

